### ISSUE TITLE
Unable to create or open database file on Linux

### ISSUE THREAD

**Issue by JustVldKsh** [ArcaeaOffline/client-pyside6#4] opened 2024-03-23 07:34 UTC
### System Details:
OS: EndeavourOS Linux x86_64
Python Version: 3.11.8

### Description of the Problem:
`sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file` whenever I try creating or opening already existing `arcaea_offline.db`  on Linux

### Expected Behaviour:
Able to create or open already existing .db file and use ArcaeaOffline like on Windows

### Additional Files (logs):
Creation: [arcaea-offline-pyside-ui-20240323-142638_debug.log](https://github.com/ArcaeaOffline/client-pyside6/files/14730649/arcaea-offline-pyside-ui-20240323-142638_debug.log)
Use of existing database: [arcaea-offline-pyside-ui-20240323-142654_debug.log](https://github.com/ArcaeaOffline/client-pyside6/files/14730652/arcaea-offline-pyside-ui-20240323-142654_debug.log)

**Comment by 283375** [comment] 2024-03-23 08:06
Thank you for reporting! I'm configuring the environment and trying to reproduce this.

**Comment by 283375** [comment] 2024-03-23 09:49
Looks like the database url works differently under linux systems. Could you please try the [fix-issue-4](https://github.com/ArcaeaOffline/client-pyside6/tree/fix-issue-4) and tell if it's working?

**Comment by JustVldKsh** [comment] 2024-03-23 10:55
Yeah, looks good to me, gonna go try setting up ocr now

**Comment by 283375** [comment] 2024-03-23 11:06
Great! I'm merging and closing this.
If there's any other issue on Linux, feel free to open one, because this application isn't tested under Linux.

**Closed** 2024-03-23 11:08 UTC
Labels: bug
